# Generated by Django 5.1.1 on 2024-10-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_date_of_birth_userprofile_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
