# Generated by Django 5.1.1 on 2024-10-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='useremail',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
