# Generated by Django 5.1.1 on 2024-10-17 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_supportticket_useremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='forgetPasswordToken',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
