# Generated by Django 5.1.1 on 2024-10-21 10:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_purchasestickets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchasesTickets',
            new_name='PurchasedTickets',
        ),
    ]
