# Generated by Django 5.1.1 on 2024-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_purchasestickets_purchasedtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedtickets',
            name='ticket_count',
            field=models.IntegerField(default=1),
        ),
    ]
